     SELECT DATE_FORMAT(DATETIME, '%H') as HOUR, COUNT(ANIMAL_ID)
       FROM ANIMAL_OUTS 
      WHERE 1=1
        AND DATE_FORMAT(DATETIME, '%H') >= '09'
        AND DATE_FORMAT(DATETIME, '%H') < '20'
   GROUP BY HOUR
   ORDER BY HOUR
    
  